import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/Topbar";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
});

const space = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased bg-blue-100`}
    >
      <body className="min-h-screen h-screen flex flex-col bg-blue-100 sm:p-6 md:p-8 rounded-lg sm:rounded-2xl">
        <Topbar />
        <div className="flex flex-col h-full md:flex-row flex-1 bg-blue-100 gap-4 md:gap-6">
          <aside className="w-full md:w-64 md:block">
            <Sidebar />
          </aside>
          <main className="flex-1 h-full overflow-y-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
